name: CD

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.20"

            - name: Build
              run: scripts/buildprod.sh

            - name: Google Cloud Auth
              uses: "google-github-actions/auth@v2"
              with:
                  credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

            - name: Setup up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v2

            - name: Build and push Docker image
              run: gcloud builds submit --tag europe-north1-docker.pkg.dev/notely-411709/notely-ar-repo/notely:latest .

            - name: Deploy to Cloud Run
              run: gcloud run deploy notely --image europe-north1-docker.pkg.dev/notely-411709/notely-ar-repo/notely:latest --region europe-north1 --allow-unauthenticated --project notely-411709 --max-instances=4
